export const seedMovies = [
  {
    slug: 'dune-part-two',
    title: 'Dune: Part Two',
    type: 'Movie',
    year: 2024,
    rating: 8.5,
    runtime: '2h 46m',
    quality: ['4K', '1080p', '720p'],
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    platforms: ['Max', 'Prime Video'],
    languages: ['English', 'Hindi'],
    poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    overview:
      'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    cast: ['Timothee Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    trailer: 'https://www.youtube.com/results?search_query=Dune+Part+Two+trailer',
    featured: true,
    trendingScore: 98,
  },
  {
    slug: 'oppenheimer',
    title: 'Oppenheimer',
    type: 'Movie',
    year: 2023,
    rating: 8.3,
    runtime: '3h 0m',
    quality: ['4K', '1080p'],
    genres: ['Biography', 'Drama', 'History'],
    platforms: ['Prime Video', 'Apple TV+'],
    languages: ['English', 'Hindi'],
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    overview:
      'The story of J. Robert Oppenheimer and the scientific race that changed the course of modern history.',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'],
    trailer: 'https://www.youtube.com/results?search_query=Oppenheimer+trailer',
    trendingScore: 94,
  },
  {
    slug: 'spider-man-across-the-spider-verse',
    title: 'Spider-Man: Across the Spider-Verse',
    type: 'Movie',
    year: 2023,
    rating: 8.6,
    runtime: '2h 20m',
    quality: ['4K', '1080p', '720p'],
    genres: ['Animation', 'Action', 'Adventure'],
    platforms: ['Netflix', 'Sony LIV'],
    languages: ['English', 'Hindi'],
    poster: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    overview:
      'Miles Morales catapults across the Multiverse, where he meets a team of Spider-People protecting its existence.',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    trailer: 'https://www.youtube.com/results?search_query=Across+the+Spider-Verse+trailer',
    trendingScore: 93,
  },
  {
    slug: 'the-last-of-us',
    title: 'The Last of Us',
    type: 'Series',
    year: 2023,
    rating: 8.7,
    runtime: '1 Season',
    quality: ['1080p', '720p'],
    genres: ['Drama', 'Thriller', 'Adventure'],
    platforms: ['Max', 'JioHotstar'],
    languages: ['English', 'Hindi'],
    poster: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg',
    overview:
      'A hardened survivor escorts a teenager across a ravaged America in a story about loss, loyalty, and hope.',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Anna Torv'],
    trailer: 'https://www.youtube.com/results?search_query=The+Last+of+Us+trailer',
    featured: true,
    trendingScore: 91,
  },
  {
    slug: 'shogun',
    title: 'Shogun',
    type: 'Series',
    year: 2024,
    rating: 8.7,
    runtime: '10 Episodes',
    quality: ['4K', '1080p'],
    genres: ['Drama', 'History', 'War'],
    platforms: ['Disney+', 'Hulu'],
    languages: ['English', 'Japanese'],
    poster: 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/2meX1nMdScFOoV4370rqHWKmXhY.jpg',
    overview:
      'A shipwrecked English pilot enters a world of political intrigue in feudal Japan.',
    cast: ['Hiroyuki Sanada', 'Cosmo Jarvis', 'Anna Sawai'],
    trailer: 'https://www.youtube.com/results?search_query=Shogun+2024+trailer',
    trendingScore: 90,
  },
  {
    slug: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    type: 'Anime',
    year: 2020,
    rating: 8.6,
    runtime: '2 Seasons',
    quality: ['1080p', '720p'],
    genres: ['Anime', 'Action', 'Fantasy'],
    platforms: ['Crunchyroll', 'Netflix'],
    languages: ['Japanese', 'Hindi', 'English'],
    poster: 'https://image.tmdb.org/t/p/w500/hFWP5HkbVEe40hrXgtCeQxoccHE.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gmECX1DvFgdUPjtio2zaL8BPYPu.jpg',
    overview:
      'A high-school student joins a secret organization of sorcerers to fight powerful curses.',
    cast: ['Junya Enoki', 'Yuma Uchida', 'Asami Seto'],
    trailer: 'https://www.youtube.com/results?search_query=Jujutsu+Kaisen+trailer',
    trendingScore: 88,
  },
]
